name: jupedsim-windows

on: 
  push:            # run on push events
    paths-ignore:  # but ignore everything in the docs subfolder 
      - 'docs/**'
    branches:
      - '**'
    tags:
      - '*'
  pull_request:    # run on pull requests
    paths-ignore:  # but ignore everything in the docs subfolder 
      - 'docs/**'
  schedule:
    - cron:  '5 0 * * *'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Cloning jpscore
      uses: actions/checkout@v3
      with:
        repository: PedestrianDynamics/jupedsim
        path: jpscore

    - name: Building jpscore
      shell: cmd
      run: |
        mkdir jpscore-build
        mkdir jpscore-install
        cd jpscore-build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%CD%/../jpscore-install -DBUILD_JPSVIS=OFF ../jpscore
        cmake --build . -j4
        cmake --install .

    - name: Uploading release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jpscore-release
        path: jpscore-install

    - name: Building jpscore debug
      shell: cmd
      run: |
        mkdir jpscore-build-debug
        mkdir jpscore-install-debug
        cd jpscore-build-debug
        cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=%CD%/../jpscore-install-debug -DBUILD_JPSVIS=OFF ../jpscore
        cmake --build . -j4
        cmake --install .

    - name: Uploading debug artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jpscore-debug
        path: jpscore-install-debug

    - name: Cloning SUMO
      uses: actions/checkout@v3
      with:
        path: sumo
        fetch-depth: 0
 
    - name: Fetching SUMO tags
      run: |
        cd sumo
        git fetch --tags --force

    - name: Cloning SUMO Libraries
      uses: actions/checkout@v3
      with:
        repository: DLR-TS/SUMOLibraries 
        path: sumolibraries

    - name: Configuring and building SUMO
      shell: cmd
      run: |
        cd sumo
        mkdir build_msvc
        cd build_msvc
        cmake -DCMAKE_CONFIG=Release -DJUPEDSIM_ENABLE=ON -DJUPEDSIM_DIR=%CD%/../../jpscore-install ..
        cmake --build . -j4

    - name: Building Examples and Tests
      run: |
        $env:PATH += ";$pwd\jpscore-deps\x64-windows\bin"
        cd sumo/build_msvc
        cmake --build . --config Release --target examples
        $env:TEXTTEST_CI_APPS = "-a sumo.extra"
        ctest --build-config Release --output-on-failure
